### ISSUE TITLE
Processing a file before promoting it to permanent storage

### ISSUE THREAD

**Issue by mfilej** [shrinerb/shrine-transloadit#7]
This week I'm giving upgrading to Shrine 3.0 another go. I'm noticing something that I think might be a difference in behaviour between 2.0x and 3.x, but maybe I'm just doing it wrong.

Just for reference, with Shrine 2.x we had this plugin working in the following way:
```
Shrine uploads to 'cache' bucket → Transloadit reads from it, writes the result to the 'store' bucket
```

With 3.x I'm seeing this flow instead:
```
Shrine uploads to 'cache' storage → Shrine uploads to 'store' storage → … 
```

So it seems the file is immediately promoted to the `store` storage, before it is even handed off to Transloadit.

I tried to write a minimal example showing this:
https://gist.github.com/mfilej/ec7afcb7227e83325cc9b56db136d659

Output:
```
-- create_table(:media_items, {:if_not_exists=>true})
D, [2020-10-07T11:04:06.576914 #60481] DEBUG -- :    (1.4ms)  CREATE TABLE IF NOT EXISTS "media_items" ("id" bigserial primary key, "item_data" text, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)
   -> 0.1391s
D, [2020-10-07T11:04:06.656286 #60481] DEBUG -- :   ActiveRecord::InternalMetadata Load (3.1ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
I, [2020-10-07T11:04:06.720899 #60481]  INFO -- : Metadata (0ms) – {:storage=>:cache, :io=>File, :uploader=>VideoUploader}
I, [2020-10-07T11:04:16.705779 #60481]  INFO -- : Upload (9984ms) – {:storage=>:cache, :location=>"ecdaa8d35fb4470bfea3ef6eb205bd11.mp4", :io=>File, :upload_options=>{}, :uploader=>VideoUploader}
D, [2020-10-07T11:04:16.707895 #60481] DEBUG -- :    (1.4ms)  BEGIN
D, [2020-10-07T11:04:16.712659 #60481] DEBUG -- :   MediaItem Create (4.5ms)  INSERT INTO "media_items" ("item_data", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["item_data", "{\"id\":\"ecdaa8d35fb4470bfea3ef6eb205bd11.mp4\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"short.mp4\",\"size\":9104458,\"mime_type\":null}}"], ["created_at", "2020-10-07 09:04:16.706182"], ["updated_at", "2020-10-07 09:04:16.706182"]]
D, [2020-10-07T11:04:16.717074 #60481] DEBUG -- :    (4.1ms)  COMMIT
I, [2020-10-07T11:04:16.896918 #60481]  INFO -- : Upload (179ms) – {:storage=>:store, :location=>"63be42c15db65784a2ac144c5722b511.mp4", :io=>VideoUploader::UploadedFile, :upload_options=>{}, :uploader=>VideoUploader}
D, [2020-10-07T11:04:16.899217 #60481] DEBUG -- :    (1.3ms)  BEGIN
D, [2020-10-07T11:04:16.902701 #60481] DEBUG -- :   MediaItem Update (3.2ms)  UPDATE "media_items" SET "item_data" = $1, "updated_at" = $2 WHERE "media_items"."id" = $3  [["item_data", "{\"id\":\"63be42c15db65784a2ac144c5722b511.mp4\",\"storage\":\"store\",\"metadata\":{\"filename\":\"short.mp4\",\"size\":9104458,\"mime_type\":null}}"], ["updated_at", "2020-10-07 09:04:16.897442"], ["id", 7]]
D, [2020-10-07T11:04:16.905304 #60481] DEBUG -- :    (2.3ms)  COMMIT
I, [2020-10-07T11:04:17.475725 #60481]  INFO -- : Transloadit (570ms) – {:processor=>:default, :uploader=>VideoUploader}
...
```

In the output you can see the two Upload lines happening before the Transloadit line. If I check the assembly on Transloadit, I can see by the `path` key that it is indeed trying to read from the `store` storage:

```json
{
  "steps": {
    "import": {
      "use": null,
      "path": "63be42c15db65784a2ac144c5722b511.mp4",
```

Is this an issue with my code?

**Comment by janko** [comment]
Yes, this might have changed in latest shrine-transloadit. It doesn't replace promotion anymore, but allows you to process as a separate step.

Is it important that Transloadit processing is performed before the cached file is promoted to permanent storage? It usually shouldn't matter, because promoting to permanent storage is fast if both temporary and permanent storages are S3.

Note that you can also have Transloadit do the promotion – https://github.com/shrinerb/shrine-transloadit#promotion. If you're using backgrounding, you should also be able to call `Attacher#transloadit_process` & `Attacher#transloadit_save` before calling `Attacher#atomic_promote`.

**Comment by mfilej** [comment]
> Is it important that Transloadit processing is performed before the cached file is promoted to permanent storage?

The way we had things working on Shrine 2.x was that we set up a policy on the upload bucket to automatically clean up old uploads after a certain amount of time. Since we don't store originals, the original being promoted is kind of redundant and we'd have to clean it up manually.

> Note that you can also have Transloadit do the promotion

That part of the readme is in fact what the code in my gist is based on, from what I can see it's more or less identical. Are you saying that this should let me skip the promotion part?

I appreciate your help.

**Comment by janko** [comment]
> Since we don't store originals, the original being promoted is kind of redundant and we'd have to clean it up manually.

Yeah, Shrine assumes you'll always want to store originals, because that way you're retaining maximum information in case you ever need to reprocess based on the original file.

> That part of the readme is in fact what the code in my gist is based on, from what I can see it's more or less identical. Are you saying that this should let me skip the promotion part?

It's easy to skip promotion if you're using backgrounding, because then you can just call `Attacher#atomic_persist` instead of `Attacher#atomic_promote` in the background job, and that should skip promotion.

Otherwise I just recommend not including the `import` step in Transloadit assembly, and let Shrine do the promotion. If I understand correctly from your gist, you want to save the original file, but you had Transloadit do it as well so it was being duplicated on primary storage.

One of these options should hopefully be good enough.
